package com.example.ghostchef;

import android.app.Dialog;
import android.os.Bundle;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import java.util.Random;

public class MealDetails extends AppCompatActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_meal_details);

    Random random = new Random();

    Meal[] meals = {
                new Meal("Protein Packed Burrito", "The Protein Packed Burrito is a delicious and nutritious meal that is filled with high-protein ingredients to fuel your body.", "Scrambled tofu\nFresh jalapeño peppers\nFresh greens\nAvocado\nZingy hot sauceBlack beans (optional)\nSriracha (optional)", "Prepare the scrambled tofu: In a non-stick pan, crumble the tofu and cook it over medium heat until it resembles scrambled eggs. Season with salt and pepper to taste.\n\nAdd the fresh jalapeño peppers: Finely chop the fresh jalapeño peppers and add them to the pan with the scrambled tofu. Cook for a few minutes until the peppers are softened.\n\nPrepare the fresh greens: Wash and chop the fresh greens of your choice, such as lettuce or spinach.\n\nSlice the avocado: Cut the avocado in half, remove the pit, and slice it into thin pieces.\n\nWarm the tortilla: Heat a tortilla in a dry pan or microwave until it is warm and pliable.\n\nAssemble the burrito: Lay the warm tortilla flat and spread a generous amount of the scrambled tofu and jalapeño mixture onto the center. Top it with fresh greens, sliced avocado, and a drizzle of zingy hot sauce. If desired, you can also add black beans or a drizzle of Sriracha for extra flavor and protein.Roll the burrito: Fold the sides of the tortilla over the filling, then roll it tightly from one end to the other, creating a burrito shape.\n\nServe and enjoy: Cut the burrito in half if desired and serve it immediately. Enjoy your Protein Packed Burrito as a satisfying and nutritious meal!"),
                new Meal("Quinoa and Black Bean Bowl", "The Quinoa and Black Bean Bowl is a flavorful and nutritious meal that combines the goodness of quinoa, black beans, and fresh vegetables.", "1 cup cooked quinoa\n1 cup black beans, cooked and drained\nFresh seasonal vegetables (e.g., chopped tomatoes, peppers, broccoli, cauliflower florets, squash, onions, garlic, etc.)\nSeasonings as desired (e.g., basil, oregano, dash of cayenne or hot sauce, etc.)\nAvocado (optional)\nSalsa (optional)\nFresh herbs (e.g., cilantro, parsley, etc.)\nLime wedges", "Cook the quinoa: Cook 1 cup of quinoa according to the package instructions. Once cooked, let it cool or chill it in the refrigerator.\n\nPrepare the vegetables: Chop your choice of fresh seasonal vegetables, such as tomatoes, peppers, broccoli, cauliflower florets, squash, onions, or garlic.\n\nMix the ingredients: In a large bowl, combine the cooked and chilled quinoa, black beans, and the chopped fresh vegetables. Add seasonings as desired, such as basil, oregano, or a dash of cayenne or hot sauce. Mix all the ingredients well.\n\nServe and garnish: Divide the quinoa and black bean mixture into bowls. Top each bowl with sliced avocado, salsa, fresh herbs like cilantro or parsley, and a squeeze of lime juice for added flavor.\n\nEnjoy: The Quinoa and Black Bean Bowl is now ready to be enjoyed! It can be served as a light lunch or dinner on its own, or you can pair it with grilled chicken or shrimp for an extra protein boost. For a low-carb alternative, you can use lettuce leaves as wraps."),
                new Meal("Salmon and Sweet Potato", "The Salmon and Sweet Potato dish is a flavorful and nutritious meal that combines the richness of salmon with the sweetness of sweet potatoes.", "Salmon fillets\nSweet potatoes\nOlive oil\nSalt and pepper\nOptional seasonings (e.g., smoked paprika, cayenne pepper, or herbs)", "Preheat the oven: Preheat your oven to 400°F (200°C).\n\nPrepare the sweet potatoes: Peel the sweet potatoes and cut them into cubes or wedges. Place them on a baking sheet lined with parchment paper. Drizzle with olive oil and season with salt and pepper. Toss to coat the sweet potatoes evenly.\n\nRoast the sweet potatoes: Place the baking sheet with the sweet potatoes in the preheated oven and roast for about 20-25 minutes, or until they are tender and lightly browned. Stir them halfway through the cooking time for even browning.\n\nPrepare the salmon: While the sweet potatoes are roasting, season the salmon fillets with salt, pepper, and any optional seasonings of your choice, such as smoked paprika or herbs.\n\nCook the salmon: Heat a non-stick skillet over medium-high heat and add a drizzle of olive oil. Place the seasoned salmon fillets in the skillet, skin-side down if applicable, and cook for about 3-4 minutes per side, or until the salmon is cooked through and flakes easily with a fork.\n\nServe and enjoy: Once the sweet potatoes are roasted and the salmon is cooked, transfer them to serving plates. Serve the salmon alongside the roasted sweet potatoes. You can garnish with fresh herbs or a squeeze of lemon juice if desired."),
                new Meal("Lean Beef Stir Fry", "The Lean Beef Stir Fry is a delicious and healthy meal that combines lean beef with a variety of vegetables.", "Lean beef strips\nOnion\nGarlic\nGinger\nAssorted vegetables of your choice (e.g., bell peppers, broccoli, carrots, snap peas, mushrooms, etc.)\nOil for cooking\nSauce of your choice (e.g., soy sauce, teriyaki sauce, hoisin sauce, etc.)\nRice or noodles for serving", "Slice the onion: Slice the onion and dice or chop the other vegetables of your choice.\n\nHeat the wok: Add oil to a wok or large skillet and heat it over medium-high heat.\n\nCook the aromatics: Add the sliced onion, minced garlic, and grated ginger to the heated wok. Cook for about 1 minute until fragrant.\n\nCook the beef: Add the lean beef strips to the wok and cook for about 1 minute until they are browned.\n\nAdd the wine: Pour in a small amount of wine and cook for another minute to deglaze the pan and enhance the flavors. (Note: If you prefer not to use wine, you can skip this step.)\n\nAdd the vegetables and sauce: Add the rest of the diced or chopped vegetables to the wok, along with the sauce of your choice. Stir everything together until the vegetables are cooked to your desired level of tenderness.\n\nServe with rice or noodles: Once the stir fry is cooked, serve it with steamed rice or noodles for a complete meal.\n\nEnjoy: Your Lean Beef Stir Fry is now ready to be enjoyed! Serve it hot and savor the delicious flavors of the tender beef and vibrant vegetables."),
                new Meal("Chicken and Vegetable Skewers", "Chicken and Vegetable Skewers are a delicious and versatile meal option that can be enjoyed during the summer or any time of the year.", "Boneless, skinless chicken thighs\nMushrooms (white button or cremini)\nCherry tomatoes\nGreen onions\nOlive oil\nBasil\nParsley\nGarlic\nLemon juice\nSalt", "Prepare the marinade: In a large bowl or freezer Ziploc bag, mix together olive oil, basil, parsley, garlic, lemon juice, and salt.\n\nMarinate the chicken: Cut the boneless, skinless chicken thighs into strips and add them to the marinade. Mix well to ensure that the chicken is coated evenly. You can refrigerate the chicken in the marinade for a few hours to allow the flavors to develop.\n\nPrepare the vegetables: Clean and prepare the mushrooms, cherry tomatoes, and green onions. Cut the green onions into one-inch pieces so that they can easily be threaded onto the skewers.\n\nThread the skewers: Build the skewers by threading the marinated chicken, mushrooms, cherry tomatoes, and green onions onto skewers. For the most precise cooking, keep like ingredients on the same skewers so you can remove them from the grill or fire as soon as they are cooked.\n\nGrill the skewers: Preheat your grill or barbecue. If using wooden skewers, soak them in water for a few hours before using to prevent them from burning. Grill the skewers on a well-oiled grate directly over the coals for 3-5 minutes per side. Then, transfer them to the indirect side of your charcoal grill to finish cooking.\n\nServe and enjoy: Once the chicken is cooked through and the vegetables are tender, remove the skewers from the grill. Serve the Chicken and Vegetable Skewers hot and enjoy them as a main course or as part of a larger meal. They pair well with rice, couscous, or homemade flatbread."),
                new Meal("Turkey and Spinach Stuffed Peppers", "Turkey and Spinach Stuffed Peppers are a delicious and healthy meal option. The combination of ground turkey, spinach, and flavorful seasonings creates a satisfying and nutritious filling.", "4 large bell peppers (any color)\n1 pound ground turkey\n1 cup cooked rice\n1 cup chopped spinach\n1/2 cup diced onion\n2 cloves garlic, minced\n1 teaspoon dried oregano\n1 teaspoon dried basil\n1/2 teaspoon salt\n1/4 teaspoon black pepper\n1 cup shredded mozzarella cheese\n1/4 cup grated Parmesan cheese\nOlive oil for drizzling", "Preheat your oven to 375°F (190°C).\n\nCut the tops off the bell peppers and remove the seeds and membranes. Place the peppers in a baking dish, cut side up.\n\nIn a large skillet, heat some olive oil over medium heat. Add the diced onion and minced garlic, and cook until the onion becomes translucent.\n\nAdd the ground turkey to the skillet and cook until it is browned and cooked through. Break up the turkey into small pieces as it cooks.\n\nStir in the cooked rice, chopped spinach, dried oregano, dried basil, salt, and black pepper. Cook for an additional 2-3 minutes, allowing the flavors to meld together.\n\nRemove the skillet from the heat and stir in the shredded mozzarella cheese. Mix well until the cheese is melted and evenly distributed.\n\nSpoon the turkey and spinach mixture into the prepared bell peppers, filling them to the top. Sprinkle grated Parmesan cheese over the stuffed peppers.\n\nDrizzle a little olive oil over the peppers to help them cook and prevent them from drying out.\n\nCover the baking dish with foil and bake in the preheated oven for 25-30 minutes, or until the peppers are tender and the filling is heated through.\n\nRemove the foil and continue baking for an additional 5 minutes, or until the cheese on top is golden and bubbly.\n\nOnce done, remove the stuffed peppers from the oven and let them cool for a few minutes before serving."),
                new Meal("Greek Yogurt Parfait", "A Greek Yogurt Parfait is a delightful and wholesome treat that combines creamy Greek yogurt with layers of fresh fruits, crunchy granola, and a drizzle of honey.", "1 cup Greek yogurt\n1/2 cup mixed berries (such as strawberries, blueberries, and raspberries)\n1/4 cup granola or nuts/seeds of your choice\n1 tablespoon honey or maple syrup\nOptional toppings: sliced banana, shredded coconut, or a drizzle of nut butter", "In a glass or a bowl, spoon a layer of Greek yogurt at the bottom.\n\nAdd a layer of mixed berries on top of the yogurt.\n\nSprinkle a layer of granola or nuts/seeds over the berries for a satisfying crunch.\n\nDrizzle honey or maple syrup over the granola for added sweetness.\n\nRepeat the layers until you have used all the ingredients, ending with a final layer of yogurt.\n\nIf desired, top the parfait with additional toppings such as sliced banana, shredded coconut, or a drizzle of nut butter."),
                new Meal("Tuna Salad Wrap", "A Tuna Salad Wrap is a quick and easy meal that is perfect for a light lunch or dinner. This versatile wrap combines the freshness of a salad with the satisfying flavors of tuna and a zesty dressing.", "1 can of tuna, drained\n1/4 cup mayonnaise\n1 tablespoon Dijon mustard\n1 tablespoon lemon juice\n1/4 cup finely chopped celery\n1/4 cup finely chopped red onion\n1/4 cup diced pickles\nSalt and pepper, to taste\n4 large tortilla wraps\nLettuce leaves\nSliced tomatoes\nSliced cucumbers\nSliced avocado (optional)", "In a medium-sized bowl, combine the drained tuna, mayonnaise, Dijon mustard, lemon juice, celery, red onion, and diced pickles. Mix well until all the ingredients are evenly combined.\n\nSeason the tuna salad mixture with salt and pepper to taste. Adjust the seasoning according to your preference.\n\nLay out the tortilla wraps on a clean surface. Place a few lettuce leaves on each wrap, followed by sliced tomatoes, cucumbers, and avocado (if desired).\n\nSpoon a generous amount of the tuna salad mixture onto the center of each tortilla wrap.\n\nFold the sides of the tortilla over the filling, then roll the wrap tightly from one end to the other, enclosing the filling completely.\n\nOptionally, you can secure the wrap with a toothpick or cut it in half for easier handling.\n\nRepeat the process for the remaining wraps."),
                new Meal("Egg and Vegetable Frittata", "An Egg and Vegetable Frittata is a versatile and delicious dish that can be enjoyed for breakfast, brunch, or any meal of the day.", "8 large eggs\n1/4 cup milk or cream\nSalt and pepper, to taste\n1 tablespoon olive oil\n1 small onion, thinly sliced\n1 bell pepper, thinly sliced\n1 zucchini, thinly sliced\n1 cup sliced mushrooms\n1 cup spinach leaves\n1/2 cup shredded cheese (such as cheddar, mozzarella, or feta)\nFresh herbs (such as parsley or basil) for garnish (optional)", "Preheat your oven to 350°F (175°C).\n\nIn a large bowl, whisk together the eggs, milk or cream, salt, and pepper until well combined. Set aside.\n\nHeat the olive oil in an oven-safe skillet over medium heat. Add the sliced onion, bell pepper, zucchini, and mushrooms. Sauté the vegetables until they are softened and slightly golden, about 5-7 minutes.\n\nAdd the spinach leaves to the skillet and cook until they are wilted, about 1-2 minutes.\n\nPour the egg mixture over the sautéed vegetables in the skillet. Stir gently to distribute the vegetables evenly.\n\nSprinkle the shredded cheese over the top of the frittata.\n\nPlace the skillet in the preheated oven and bake for 15-20 minutes, or until the frittata is set and the top is golden brown.\n\nRemove the frittata from the oven and let it cool for a few minutes. It will continue to set as it cools.\n\nOptionally, garnish the frittata with fresh herbs, such as parsley or basil, for added flavor and presentation.\n\nSlice the frittata into wedges and serve warm."),
                new Meal("Lean Beef Chili", "Lean Beef Chili is a hearty and flavorful dish that is perfect for chilly days or when you're craving a comforting meal.", "1 pound lean ground beef\n1 onion, diced\n2 cloves garlic, minced\n1 bell pepper, diced\n1 jalapeño pepper, seeded and minced (optional, for heat)\n1 can (14 ounces) diced tomatoes\n1 can (14 ounces) tomato sauce\n1 can (14 ounces) kidney beans, drained and rinsed\n1 can (14 ounces) black beans, drained and rinsed\n1 cup beef broth\n2 tablespoons chili powder\n1 tablespoon cumin\n1 teaspoon paprika\n1/2 teaspoon dried oregano\nSalt and pepper, to taste\nOlive oil, for cooking\nOptional toppings: shredded cheese, sour cream, chopped green onions, cilantro, avocado", "Heat a large pot or Dutch oven over medium heat. Add a drizzle of olive oil and the diced onion. Sauté the onion until it becomes translucent, about 3-4 minutes.\n\nAdd the minced garlic, diced bell pepper, and minced jalapeño pepper (if using). Cook for another 2-3 minutes until the peppers have softened.\n\nPush the onion and pepper mixture to one side of the pot and add the lean ground beef to the other side. Cook the beef, breaking it up with a spoon, until it is browned and no longer pink.\n\nStir in the chili powder, cumin, paprika, dried oregano, salt, and pepper. Cook for another minute to toast the spices and infuse the flavors.\n\nAdd the diced tomatoes, tomato sauce, kidney beans, black beans, and beef broth to the pot. Stir everything together until well combined.\n\nBring the chili to a simmer, then reduce the heat to low. Cover the pot and let the chili cook for at least 30 minutes, stirring occasionally to prevent sticking.\n\nTaste the chili and adjust the seasoning with additional salt, pepper, or spices according to your preference.\n\nServe the Lean Beef Chili hot in bowls. Garnish with your favorite toppings, such as shredded cheese, sour cream, chopped green onions, cilantro, or avocado."),
                new Meal("Chicken and Quinoa Salad", "Chicken and Quinoa Salad is a nutritious and flavorful dish that combines tender chicken, fluffy quinoa, and a variety of fresh vegetables.", "2 cups cooked quinoa\n2 cups cooked chicken breast, shredded or diced\n1 cup cherry tomatoes, halved\n1 cup cucumber, diced\n1/2 cup feta cheese, crumbled\n1/4 cup Kalamata olives, pitted and halved\n1/4 cup red onion, thinly sliced\nFresh herbs (such as parsley or basil), chopped\nSalt and pepper, to taste\nLemon wedges, for serving (optional)", "In a large bowl, combine the cooked quinoa, cooked chicken breast, cherry tomatoes, cucumber, feta cheese, Kalamata olives, red onion, and fresh herbs. Toss gently to mix all the ingredients together.\n\nSeason the salad with salt and pepper to taste. Adjust the seasoning according to your preference.\n\nServe the Chicken and Quinoa Salad immediately, or refrigerate it for a few hours to allow the flavors to meld together.\n\nOptionally, serve the salad with lemon wedges on the side for a tangy citrus flavor."),
                new Meal("Turkey and Vegetable Meatballs", "Turkey and Vegetable Meatballs are a healthy twist on traditional meatballs. This recipe combines lean ground turkey with a medley of vegetables, resulting in moist and flavorful meatballs that are packed with nutrients.", "1 pound ground turkey\n1/2 cup grated zucchini, excess moisture squeezed out\n1/2 cup grated carrot\n1/4 cup finely chopped onion\n2 cloves garlic, minced\n1/4 cup breadcrumbs\n1/4 cup grated Parmesan cheese\n1/4 cup chopped fresh parsley\n1 large egg\n1 teaspoon dried oregano\n1/2 teaspoon salt\n1/4 teaspoon black pepper\nOlive oil, for cooking", "Preheat your oven to 400°F (200°C) and line a baking sheet with parchment paper.\n\nIn a large bowl, combine the ground turkey, grated zucchini, grated carrot, chopped onion, minced garlic, breadcrumbs, grated Parmesan cheese, chopped parsley, egg, dried oregano, salt, and black pepper. Mix well until all the ingredients are evenly combined.\n\nShape the mixture into meatballs, about 1-2 inches in diameter, and place them on the prepared baking sheet. Leave a little space between each meatball to ensure even cooking.\n\nDrizzle the meatballs with a little olive oil to help them brown and develop a crispy exterior.\n\nBake the meatballs in the preheated oven for 20-25 minutes, or until they are cooked through and browned on the outside.\n\nOnce done, remove the meatballs from the oven and let them cool for a few minutes before serving."),
                new Meal("Protein Packet Smoothie", "A Protein Packed Smoothie is a delicious and nutritious way to fuel your body and start your day off right.", "1 ripe banana\n1 cup frozen mixed berries (such as strawberries, blueberries, and raspberries)\n1 cup unsweetened almond milk (or your preferred milk)\n1 scoop protein powder (such as whey, plant-based, or collagen)\n1 tablespoon almond butter or peanut butter\n1 tablespoon chia seeds or flaxseeds\n1 teaspoon honey or maple syrup (optional, for sweetness)\nIce cubes (optional, for a colder smoothie)", "Place all the ingredients into a blender: the ripe banana, frozen mixed berries, unsweetened almond milk, protein powder, almond butter or peanut butter, chia seeds or flaxseeds, and honey or maple syrup (if using).\n\nBlend on high speed until all the ingredients are well combined and the smoothie is creamy and smooth. If desired, add a few ice cubes to make the smoothie colder and thicker.\n\nTaste the smoothie and adjust the sweetness by adding more honey or maple syrup if desired. Blend again briefly to incorporate any additional ingredients.\n\nPour the smoothie into a glass or to-go cup and enjoy it immediately."),
                new Meal("Pulled Chicken Sandwich", "A Pulled Chicken Sandwich is a flavorful and satisfying meal that is perfect for lunch or dinner.", "2 pounds boneless, skinless chicken breasts or thighs\n1 onion, sliced\n2 cloves garlic, minced\n1 cup chicken broth\n1/2 cup barbecue sauce\n2 tablespoons brown sugar\n1 tablespoon Worcestershire sauce\n1 tablespoon apple cider vinegar\n1 teaspoon smoked paprika\n1/2 teaspoon chili powder\nSalt and pepper, to taste\nHamburger buns or sandwich rolls\nOptional toppings: coleslaw, pickles, sliced onions", "Place the chicken breasts or thighs in a slow cooker. Add the sliced onion and minced garlic.\n\nIn a separate bowl, whisk together the chicken broth, barbecue sauce, brown sugar, Worcestershire sauce, apple cider vinegar, smoked paprika, chili powder, salt, and pepper. Pour this mixture over the chicken in the slow cooker.\n\nCover the slow cooker and cook on low heat for 6-8 hours, or on high heat for 3-4 hours, until the chicken is tender and easily shreds with a fork.\n\nOnce the chicken is cooked, remove it from the slow cooker and transfer it to a cutting board. Use two forks to shred the chicken into smaller pieces.\n\nMeanwhile, pour the liquid from the slow cooker into a saucepan. Bring the liquid to a boil over medium-high heat and let it simmer until it thickens and reduces slightly, about 10 minutes. This will become the sauce for the pulled chicken.\n\nReturn the shredded chicken to the slow cooker and pour the thickened sauce over it. Stir well to coat the chicken evenly.\n\nToast the hamburger buns or sandwich rolls, if desired. Place a generous amount of the pulled chicken mixture onto each bun or roll.\n\nAdd your favorite toppings, such as coleslaw, pickles, or sliced onions, to customize your Pulled Chicken Sandwich."),
                new Meal("Beef and Broccoli Stir-Fry", "Beef and Broccoli Stir-Fry is a classic and delicious dish that brings together tender beef, crisp broccoli, and a flavorful sauce.", "1 pound flank steak or sirloin steak, thinly sliced\n3 cups broccoli florets\n2 cloves garlic, minced\n1/4 cup soy sauce\n2 tablespoons oyster sauce\n1 tablespoon cornstarch\n1 tablespoon brown sugar or honey\n1 tablespoon vegetable oil\n1/2 teaspoon sesame oil (optional)\nSalt and pepper, to taste\nRice or noodles, for serving", "In a small bowl, whisk together the soy sauce, oyster sauce, cornstarch, brown sugar or honey, and a pinch of salt and pepper. Set aside.\n\nHeat the vegetable oil in a large skillet or wok over medium-high heat. Add the minced garlic and cook for about 30 seconds until fragrant.\n\nAdd the thinly sliced beef to the skillet and stir fry for 2-3 minutes, or until it is browned and cooked to your desired level of doneness. Remove the beef from the skillet and set it aside.\n\nIn the same skillet, add the broccoli florets and a splash of water. Cover the skillet with a lid and steam the broccoli for about 2-3 minutes, or until it becomes bright green and slightly tender.\n\nReturn the cooked beef to the skillet with the broccoli. Pour the sauce mixture over the beef and broccoli, stirring well to coat everything evenly. Continue cooking for another 1-2 minutes, or until the sauce thickens and coats the beef and broccoli.\n\nIf desired, drizzle the sesame oil over the stir-fry and give it a final stir.\n\nServe the Beef and Broccoli Stir-Fry hot over a bed of rice or noodles."),
                new Meal("Salmon and Avocado Salad", "Salmon and Avocado Salad is a refreshing and nutritious dish that combines the richness of salmon with the creaminess of avocado.", "1 pound salmon fillets\n4 cups mixed salad greens\n1 avocado, sliced\n1 cup cherry tomatoes, halved\n1/4 red onion, thinly sliced\n1/4 cup chopped fresh cilantro or parsley\nJuice of 1 lemon\n2 tablespoons olive oil\nSalt and pepper, to taste", "Preheat your oven to 375°F (190°C). Season the salmon fillets with salt and pepper, and place them on a baking sheet lined with parchment paper.\n\nBake the salmon in the preheated oven for 12-15 minutes, or until it is cooked through and flakes easily with a fork. Once cooked, remove the salmon from the oven and let it cool for a few minutes.\n\nWhile the salmon is cooling, prepare the salad. In a large bowl, combine the mixed salad greens, sliced avocado, cherry tomatoes, thinly sliced red onion, and chopped cilantro or parsley.\n\nIn a small bowl, whisk together the lemon juice, olive oil, salt, and pepper to make the dressing.\n\nBreak the cooked salmon into smaller pieces and add it to the salad bowl. Drizzle the dressing over the salad and gently toss to evenly coat all the ingredients.\n\nDivide the Salmon and Avocado Salad among serving plates or bowls."),
                new Meal("Turkey and Quinoa Stuffed Bell Peppers", "Turkey and Quinoa Stuffed Bell Peppers are a delicious and healthy meal option that combines flavorful ground turkey, nutritious quinoa, and vibrant bell peppers.", "4 bell peppers (any color), tops removed and seeds removed\n1 pound ground turkey\n1 cup cooked quinoa\n1/2 cup diced onion\n1/2 cup diced zucchini\n1/2 cup diced red bell pepper\n1/2 cup diced mushrooms\n2 cloves garlic, minced\n1 teaspoon dried oregano\n1/2 teaspoon dried basil\n1/2 teaspoon paprika\nSalt and pepper, to taste\n1 cup tomato sauce\n1/4 cup grated Parmesan cheese (optional)", "Preheat your oven to 375°F (190°C). Place the hollowed bell peppers in a baking dish and set aside.\n\nIn a large skillet, cook the ground turkey over medium heat until it is no longer pink. Break up the turkey into smaller pieces as it cooks.\n\nAdd the diced onion, zucchini, red bell pepper, mushrooms, minced garlic, dried oregano, dried basil, paprika, salt, and pepper to the skillet with the cooked turkey. Sauté the mixture for 5-7 minutes, or until the vegetables are tender.\n\nStir in the cooked quinoa and tomato sauce. Cook for an additional 2-3 minutes, allowing the flavors to blend together.\n\nSpoon the turkey and quinoa mixture into the hollowed bell peppers, filling them evenly. If desired, sprinkle grated Parmesan cheese on top of each stuffed pepper.\n\nCover the baking dish with foil and bake in the preheated oven for 25-30 minutes, or until the bell peppers are tender and the filling is heated through.\n\nRemove the foil and continue baking for an additional 5-10 minutes, or until the cheese (if using) is melted and golden.\n\nOnce done, remove the stuffed bell peppers from the oven and let them cool for a few minutes before serving."),
                new Meal("Mediterranean Chicken Bowl", "A Mediterranean Chicken Bowl is a flavorful and vibrant dish that combines tender chicken with a variety of fresh vegetables, aromatic herbs, and tangy dressings.", "1 pound boneless, skinless chicken breasts\n2 tablespoons olive oil\n2 teaspoons dried oregano\n1 teaspoon garlic powder\nSalt and pepper, to taste\n4 cups mixed salad greens\n1 cup cherry tomatoes, halved\n1 cucumber, sliced\n1/2 red onion, thinly sliced\n1/2 cup Kalamata olives\n1/4 cup crumbled feta cheese\nJuice of 1 lemon\n2 tablespoons extra-virgin olive oil\nOptional toppings: chopped fresh parsley, hummus, tzatziki sauce", "Preheat your oven to 400°F (200°C). Season the chicken breasts with olive oil, dried oregano, garlic powder, salt, and pepper. Place the seasoned chicken on a baking sheet lined with parchment paper.\n\nBake the chicken in the preheated oven for 20-25 minutes, or until it is cooked through and reaches an internal temperature of 165°F (74°C). Once cooked, remove the chicken from the oven and let it rest for a few minutes before slicing it into strips.\n\nWhile the chicken is resting, prepare the salad. In a large bowl, combine the mixed salad greens, cherry tomatoes, cucumber slices, thinly sliced red onion, Kalamata olives, and crumbled feta cheese.\n\nIn a small bowl, whisk together the lemon juice and extra-virgin olive oil to make the dressing. Season with salt and pepper to taste.\n\nAdd the sliced chicken to the salad bowl. Drizzle the dressing over the salad and gently toss to evenly coat all the ingredients.\n\nDivide the Mediterranean Chicken Bowl among serving plates or bowls.\n\nIf desired, top the bowl with additional toppings such as chopped fresh parsley, hummus, or tzatziki sauce for extra flavor and creaminess."),
                new Meal("Egg and Avocado Toast", "Egg and Avocado Toast is a simple and nutritious meal that combines the creaminess of avocado with the protein-packed goodness of eggs.", "2 slices of bread (whole wheat, sourdough, or your preferred choice)\n1 ripe avocado\n2 eggs\nSalt and pepper, to taste\nOptional toppings: sliced tomatoes, microgreens, hot sauce, or crumbled feta cheese", "Toast the bread slices to your desired level of crispness.\n\nWhile the bread is toasting, slice the avocado in half and remove the pit. Scoop out the avocado flesh into a bowl and mash it with a fork. Season with salt and pepper to taste.\n\nIn a non-stick skillet, cook the eggs according to your preference (fried, scrambled, or poached). Season the eggs with salt and pepper.\n\nOnce the bread is toasted, spread a generous amount of mashed avocado onto each slice.\n\nPlace the cooked eggs on top of the avocado spread. Gently press them down to help them adhere to the toast.\n\nAdd any optional toppings you desire, such as sliced tomatoes, microgreens, hot sauce, or crumbled feta cheese."),
                new Meal("Protein Packed Cottage Cheese Bowl", "A Protein Packed Cottage Cheese Bowl is a nutritious and satisfying meal option that combines creamy cottage cheese with an array of flavorful and healthy toppings.", "1 cup cottage cheese\n1/2 cup mixed berries (such as strawberries, blueberries, and raspberries)\n1/4 cup granola or nuts/seeds of your choice\n1 tablespoon honey or maple syrup (optional)\n1 tablespoon chia seeds or flaxseeds (optional)\nFresh mint leaves, for garnish (optional)", "In a bowl, scoop the cottage cheese and spread it evenly.\n\nTop the cottage cheese with the mixed berries, arranging them in a visually appealing manner.\n\nSprinkle the granola or nuts/seeds over the berries, adding a satisfying crunch.\n\nIf desired, drizzle honey or maple syrup over the bowl for added sweetness.\n\nFor an extra nutritional boost, sprinkle chia seeds or flaxseeds on top.\n\nGarnish the bowl with fresh mint leaves, if desired, for a pop of freshness.")
    };

    Dialog trenDialog = new Dialog(this);
    trenDialog.setContentView(R.layout.dialog_tren);

    ImageButton buttonOpenDialog = findViewById(R.id.buttonOpenDialog);
    Button buttonCloseDialog = trenDialog.findViewById(R.id.buttonCloseDialog);

    Button buttonGenerateMeal = findViewById(R.id.buttonGenerateMeal);

    ImageView mealImage = findViewById(R.id.ImageViewMealImage);
    TextView mealTitle = findViewById(R.id.TextViewMealTitle);
    TextView mealDescription = findViewById(R.id.TextViewMealDescription);
    TextView mealIngredients = findViewById(R.id.TextViewMealIngredients);
    TextView mealInstructions = findViewById(R.id.TextViewMealInstructions);

    buttonOpenDialog.setOnClickListener(v -> trenDialog.show());

    buttonCloseDialog.setOnClickListener(v -> trenDialog.dismiss());

    buttonGenerateMeal.setOnClickListener(v -> {
      int randomMeal = random.nextInt(meals.length);

      mealImage.setImageResource(getResources().getIdentifier("meal_image_" + randomMeal, "drawable", getPackageName()));
      mealTitle.setText(meals[randomMeal].name);
      mealDescription.setText(meals[randomMeal].description);
      mealIngredients.setText(meals[randomMeal].ingredients);
      mealInstructions.setText(meals[randomMeal].instructions);
    });
  }
}